export const cardInfo = [
  {
    imgSrc: '/characters_img/Abadango_Cluster_Princess.png',
    name: 'Abadango Cluster Princess',
  },
  {
    imgSrc: '/characters_img/abradolf_lincler.png',
    name: 'Abradolf Lincler',
  },
  { imgSrc: '/characters_img/adjudicator_rick.png', name: 'Adjudicator Rick' },
  { imgSrc: '/characters_img/agency_director.png', name: 'Agency Director' },
  { imgSrc: '/characters_img/alan_rails.png', name: 'Alan Rails' },
  { imgSrc: '/characters_img/albert_einstein.png', name: 'Albert Einstein' },
  { imgSrc: '/characters_img/alexander.png', name: 'Alexander' },
  { imgSrc: '/characters_img/alien_googah.png', name: 'Alien Googah' },
  { imgSrc: '/characters_img/alien_morty.png', name: 'Alien Morty' },
  { imgSrc: '/characters_img/alien_rick.png', name: 'Alien Rick' },
  { imgSrc: '/characters_img/Amish_cyborg.png', name: 'Amish Cyborg' },
  { imgSrc: '/characters_img/annie.png', name: 'Annie' },
  { imgSrc: '/characters_img/antenna_morty.png', name: 'Antenna Morty' },
  { imgSrc: '/characters_img/antenna_rick.png', name: 'Antenna Rick' },
  {
    imgSrc: '/characters_img/ants_johnson.png',
    name: 'Ants in my Eyes Johnson',
  },
  { imgSrc: '/characters_img/Beth_Smith.png', name: 'Beth Smith' },
  { imgSrc: '/characters_img/Jerry_Smith.png', name: 'Jerry Smith' },
  { imgSrc: '/characters_img/morty_smith.png', name: 'Morty Smith' },
  { imgSrc: '/characters_img/rick_sanchez.png', name: 'Rick Sanchez' },
  { imgSrc: '/characters_img/summer_smith.png', name: 'Summer Smith' },
];
